#note: autogenerated from genRPCModule.js
class BionetApi():
	def __init__(self,bionetClient):
		self.bionetClient = bionetClient
	async def requestSendMTA(self,requestID,description,cb):
		rpcRequest = {
			"method":"requestSendMTA",
			"args":[requestID,description]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def requestBuyShippingLabel(self,requestID,cb):
		rpcRequest = {
			"method":"requestBuyShippingLabel",
			"args":[requestID]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def requestPrintShippingLabel(self,requestID,cb):
		rpcRequest = {
			"method":"requestPrintShippingLabel",
			"args":[requestID]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def printShippingLabel(self,address,cb):
		rpcRequest = {
			"method":"printShippingLabel",
			"args":[address]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def getWorkbench(self,cb):
		rpcRequest = {
			"method":"getWorkbench",
			"args":[]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def workbenchTree(self,cb):
		rpcRequest = {
			"method":"workbenchTree",
			"args":[]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def getFavLocations(self,cb):
		rpcRequest = {
			"method":"getFavLocations",
			"args":[]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def favLocationsTree(self,cb):
		rpcRequest = {
			"method":"favLocationsTree",
			"args":[]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def saveFavLocation(self,material,imageData,doPrint,cb):
		rpcRequest = {
			"method":"saveFavLocation",
			"args":[material,imageData,doPrint]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def getChildren(self,id,cb):
		rpcRequest = {
			"method":"getChildren",
			"args":[id]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def saveInWorkbench(self,material,imageData,doPrint,cb):
		rpcRequest = {
			"method":"saveInWorkbench",
			"args":[material,imageData,doPrint]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def getID(self,cb):
		rpcRequest = {
			"method":"getID",
			"args":[]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def clearDeleted(self,cb):
		rpcRequest = {
			"method":"clearDeleted",
			"args":[]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def undelete(self,key,cb):
		rpcRequest = {
			"method":"undelete",
			"args":[key]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def delPhysical(self,id,cb):
		rpcRequest = {
			"method":"delPhysical",
			"args":[id]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def delVirtual(self,id,cb):
		rpcRequest = {
			"method":"delVirtual",
			"args":[id]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def physicalAutocomplete(self,query,cb):
		rpcRequest = {
			"method":"physicalAutocomplete",
			"args":[query]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def addToCart(self,physical_id,name,cb):
		rpcRequest = {
			"method":"addToCart",
			"args":[physical_id,name]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def delFromCart(self,physical_id,cb):
		rpcRequest = {
			"method":"delFromCart",
			"args":[physical_id]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def emptyCart(self,cb):
		rpcRequest = {
			"method":"emptyCart",
			"args":[]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def getType(self,name,cb):
		rpcRequest = {
			"method":"getType",
			"args":[name]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def createAutocomplete(self,type,query,cb):
		rpcRequest = {
			"method":"createAutocomplete",
			"args":[type,query]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def saveVirtual(self,material,cb):
		rpcRequest = {
			"method":"saveVirtual",
			"args":[material]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def savePhysical(self,material,imageData,doPrint,cb):
		rpcRequest = {
			"method":"savePhysical",
			"args":[material,imageData,doPrint]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def elasticSearch(self,query,cb):
		rpcRequest = {
			"method":"elasticSearch",
			"args":[query]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def inventoryTree(self,cb):
		rpcRequest = {
			"method":"inventoryTree",
			"args":[]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def getParentPath(self,id,cb):
		rpcRequest = {
			"method":"getParentPath",
			"args":[id]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def getLocationPath(self,id,cb):
		rpcRequest = {
			"method":"getLocationPath",
			"args":[id]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def getPath(self,id,cb):
		rpcRequest = {
			"method":"getPath",
			"args":[id]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def getImmediateChildren(self,path,key,cb):
		rpcRequest = {
			"method":"getImmediateChildren",
			"args":[path,key]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def getLocationPathChildren(self,id,cb):
		rpcRequest = {
			"method":"getLocationPathChildren",
			"args":[id]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def getVirtualBy(self,field,value,cb):
		rpcRequest = {
			"method":"getVirtualBy",
			"args":[field,value]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def getBy(self,field,value,cb):
		rpcRequest = {
			"method":"getBy",
			"args":[field,value]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def search(self,query,cb):
		rpcRequest = {
			"method":"search",
			"args":[query]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def getUser(self,id,cb):
		rpcRequest = {
			"method":"getUser",
			"args":[id]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def delUser(self,id,cb):
		rpcRequest = {
			"method":"delUser",
			"args":[id]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def saveUser(self,id,userData,cb):
		rpcRequest = {
			"method":"saveUser",
			"args":[id,userData]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def getPeers(self,cb):
		rpcRequest = {
			"method":"getPeers",
			"args":[]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def peerSearchOld(self,query,cb):
		rpcRequest = {
			"method":"peerSearchOld",
			"args":[query]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def peerBlast(self,query,cb):
		rpcRequest = {
			"method":"peerBlast",
			"args":[query]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def emptyRequestTrash(self,cb):
		rpcRequest = {
			"method":"emptyRequestTrash",
			"args":[]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def changeRequestTrashed(self,id,trashed,cb):
		rpcRequest = {
			"method":"changeRequestTrashed",
			"args":[id,trashed]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def changeRequestStatus(self,id,status,cb):
		rpcRequest = {
			"method":"changeRequestStatus",
			"args":[id,status]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def requestMaterial(self,peerID,id,cb):
		rpcRequest = {
			"method":"requestMaterial",
			"args":[peerID,id]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def freegenesCreatePlate(self,parent_id,name,cb):
		rpcRequest = {
			"method":"freegenesCreatePlate",
			"args":[parent_id,name]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def freegenesCreatePart(self,virtual_id,parent_id,name,cb):
		rpcRequest = {
			"method":"freegenesCreatePart",
			"args":[virtual_id,parent_id,name]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def getPandadocStatus(self,cb):
		rpcRequest = {
			"method":"getPandadocStatus",
			"args":[]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def foo_user(self,cb):
		rpcRequest = {
			"method":"foo_user",
			"args":[]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def testStream(self,cb):
		rpcRequest = {
			"method":"testStream",
			"args":[]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def listDeleted(self,cb):
		rpcRequest = {
			"method":"listDeleted",
			"args":[]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def cartStream(self,cb):
		rpcRequest = {
			"method":"cartStream",
			"args":[]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def clearRequests(self,cb):
		rpcRequest = {
			"method":"clearRequests",
			"args":[]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def getRequests(self,cb):
		rpcRequest = {
			"method":"getRequests",
			"args":[]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def recentChanges(self,cb):
		rpcRequest = {
			"method":"recentChanges",
			"args":[]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def getUsers(self,cb):
		rpcRequest = {
			"method":"getUsers",
			"args":[]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def getInventoryRoot(self,cb):
		rpcRequest = {
			"method":"getInventoryRoot",
			"args":[]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def getPeerInfo(self,cb):
		rpcRequest = {
			"method":"getPeerInfo",
			"args":[]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def getStatus(self,cb):
		rpcRequest = {
			"method":"getStatus",
			"args":[]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def foo(self,cb):
		rpcRequest = {
			"method":"foo",
			"args":[]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def checkMasterPassword(self,password,cb):
		rpcRequest = {
			"method":"checkMasterPassword",
			"args":[password]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def createUser(self,username,email,password,opts,cb):
		rpcRequest = {
			"method":"createUser",
			"args":[username,email,password,opts]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def getRequestStatus(self,pandadocID,cb):
		rpcRequest = {
			"method":"getRequestStatus",
			"args":[pandadocID]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def getRequest(self,key,cb):
		rpcRequest = {
			"method":"getRequest",
			"args":[key]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def createRequest(self,virtual_id,data,cb):
		rpcRequest = {
			"method":"createRequest",
			"args":[virtual_id,data]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def getByHumanID(self,humanID,cb):
		rpcRequest = {
			"method":"getByHumanID",
			"args":[humanID]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def verifyUser(self,code,cb):
		rpcRequest = {
			"method":"verifyUser",
			"args":[code]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def requestPasswordReset(self,emailOrName,cb):
		rpcRequest = {
			"method":"requestPasswordReset",
			"args":[emailOrName]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def checkPasswordResetCode(self,resetCode,cb):
		rpcRequest = {
			"method":"checkPasswordResetCode",
			"args":[resetCode]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def completePasswordReset(self,resetCode,password,cb):
		rpcRequest = {
			"method":"completePasswordReset",
			"args":[resetCode,password]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def blast(self,query,opts,cb):
		rpcRequest = {
			"method":"blast",
			"args":[query,opts]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def get(self,id,cb):
		rpcRequest = {
			"method":"get",
			"args":[id]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def requestLocalMaterial(self,id,requesterEmail,physicalAddress,name,org,msg,cb):
		rpcRequest = {
			"method":"requestLocalMaterial",
			"args":[id,requesterEmail,physicalAddress,name,org,msg]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def searchVirtuals(self,query,opts,cb):
		rpcRequest = {
			"method":"searchVirtuals",
			"args":[query,opts]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def searchPhysicals(self,query,opts,cb):
		rpcRequest = {
			"method":"searchPhysicals",
			"args":[query,opts]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def blastStream(self,query,opts,cb):
		rpcRequest = {
			"method":"blastStream",
			"args":[query,opts]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
	async def peerSearch(self,methodName,query,opts,cb):
		rpcRequest = {
			"method":"peerSearch",
			"args":[methodName,query,opts]
		}
		await self.bionetClient.arpc(rpcRequest, cb)
